### PR TITLE
Fix: Wait for Sequencer gRPC server to start before starting other components

### LINKED ISSUE #47: Flaky startup timing between Conductor and Sequencer
i think there's a flaky startup issue because of timing of sequencer being completely ready and conductor trying to get blockheight

every couple times ill get this log in conductor

```
2024-04-16T16:30:19.944466Z ERROR run_until_stopped: astria_conductor::sequencer: error={"0": "first latest height from sequencer was bad", "1": "{"0": "HTTP error", "1": "error sending request for url (http://127.0.0.1:26657/): error trying to connect: tcp connect error: Connection refused (o

2024-04-16T16:30:19.944489Z ERROR astria_conductor::conductor: reason={"0": "task `{name}` failed", "1": "task returned with error", "2": "first latest height from sequencer was bad", "3": "{"0": "HTTP error", "1": "error sending request for url (http://127.0.0.1:26657/): error trying to conne
```

### PR DESCRIPTION
**Pull request by sambukowski**
Solves the problem of Conductor and Composer starting to quickly after Sequencer starts, causing both of them to crash or hang until they are restarted.

Adds a `ReadyChecker` to the process runner that allows the user to pass a callback function that can perform any required startup checks for a given process.

closes #47

### CODE REVIEW

File: internal/processrunner/readychecker.go [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+	// CallBackName is the name of the callback function and is used for logging purposes.
+	CallBackName string
+	// Callback is the anonymous function that will be called to check if all
+	// startup requirements for the process have been completed. The function
+	// should return true if all startup checks are complete, and false if any
+	// startup checks have not completed.
+	Callback      func() bool
+	RetryCount    int
+	RetryInterval time.Duration
+	// HaltIfFailed is a flag that determines if the process should halt the app or
```
Comment (steezeburger) [inline internal/processrunner/readychecker.go:31]: Docs nit but I think these helpful comments describing the fields should go on the struct definition where the fields are defined. I think that's where a newcomer would be likely to look first.

File: internal/processrunner/readychecker.go [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+	return ReadyChecker{
+		callBackName:  opts.CallBackName,
+		callback:      opts.Callback,
+		retryCount:    opts.RetryCount,
+		retryInterval: opts.RetryInterval,
+		haltIfFailed:  opts.HaltIfFailed,
+	}
+}
+
+// WaitUntilReady calls the ReadyChecker.callback function N number of times,
```
Comment (steezeburger) [inline internal/processrunner/readychecker.go:47]:
```suggestion
// waitUntilReady calls the ReadyChecker.callback function N number of times,
```

File: cmd/devtools/run.go [hunk 3]
```diff
@@ -221,3 +238,38 @@ func getFlagPathOrPanic(c *cobra.Command, flagName string, defaultValue string)
 		return defaultValue
 	}
 }
+
+// gRPCServerIsOK builds an anonymous function for use in a ProcessRunner
+// ReadyChecker callback. The anonymous function checks if the gRPC server that
+// is started by the sequencer is OK by making an HTTP request to the health
+// endpoint. Being able to connect to the gRPC server is a requirement for both
+// the Conductor and Composer services.
+func gRPCServerIsOK(envPath string) func() bool {
```
Comment (steezeburger) [inline cmd/devtools/run.go:247]: How do you feel about renaming this to something like `getSequencerOKCallback` or similar? I think it's more accurate.

**Review by steezeburger — CHANGES_REQUESTED** [review]

**Review by steezeburger — APPROVED** [review]
